#!/bin/bash
USAGE='backport [{hash}[,{hash}]* | --continue]'
LONG_USAGE="Gebruik het commando om hashes te backporten, bij het falen van een merge fix de merge issue en doe 'git backport --continue {overgeleven hashes}'"
. git-sh-setup

require_work_tree_exists

if [ $# -eq 0 ]; then
	usage
fi

cd_to_toplevel

CURBRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURBRANCH" = "master" ]; then
	echo "Voer backport uit op de branch waar je naartoe wilt backporten, niet op master."
	exit 1
fi

echo EduArte pullen
git pull
echo Cobra fetchen
git fetch git@github.com:topicusonderwijs/cobra.git
  
STATUS=0
HASHES=$(echo $1|tr "," "\n")
REMAINING=""
for HASH in $HASHES; do
	if [ $STATUS -eq 0 ]; then
		echo "$HASH:"
		LOG=$(git log --oneline -1 $HASH)
		git cherry-pick $HASH
		STATUS=$?
	else
		if [ -z "$REMAINING" ]; then
			REMAINING=$HASH
		else
			REMAINING="$REMAINING,$HASH"
		fi
	fi
done

if [ -z "$REMAINING" ]; then
	echo Nu met de hand een 'git push' doen indien gewenst
else
	echo Er is iets mis gegaan, fix het probleem en ga verder door het uitvoeren van
	echo -e "\tgit backport $REMAINING"
fi
